# Generated by Django 5.0.7 on 2024-08-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('rank', models.CharField(blank=True, choices=[('3Y', '3 юнацький'), ('2Y', '2 юнацький'), ('1Y', '1 юнацький'), ('3A', '3 дорослий'), ('2A', '2 дорослий'), ('1A', '1 дорослий'), ('CMS', 'КМС'), ('MS', 'МС'), ('MSMK', 'МСМК')], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DistanceToDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('fr', 'Вільний стиль'), ('bk', 'На спині'), ('br', 'Брас'), ('bt', 'Батерфляй'), ('im', 'Комплекс')], max_length=2)),
                ('distance', models.CharField(choices=[('25m', '25 метрів'), ('50m', '50 метрів'), ('100m', '100 метрів'), ('200m', '200 метрів'), ('400m', '400 метрів'), ('800m', '800 метрів'), ('1500m', '1500 метрів'), ('1k', '1 кілометр'), ('1250m', '1250 метрів'), ('2k', '2 кілометра'), ('2.5k', '2,5 кілометра'), ('5k', '5 кілометрів'), ('7.5k', '7,5 кілометрів'), ('10k', '10 кілометрів')], max_length=5)),
                ('day', models.DateField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('fr', 'Вільний стиль'), ('bk', 'На спині'), ('br', 'Брас'), ('bt', 'Батерфляй'), ('im', 'Комплекс')], max_length=2)),
                ('distance', models.CharField(choices=[('25m', '25 метрів'), ('50m', '50 метрів'), ('100m', '100 метрів'), ('200m', '200 метрів'), ('400m', '400 метрів'), ('800m', '800 метрів'), ('1500m', '1500 метрів'), ('1k', '1 кілометр'), ('1250m', '1250 метрів'), ('2k', '2 кілометра'), ('2.5k', '2,5 кілометра'), ('5k', '5 кілометрів'), ('7.5k', '7,5 кілометрів'), ('10k', '10 кілометрів')], max_length=5)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
