# Generated by Django 5.0.7 on 2024-08-10 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distancetoday',
            name='competitions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats_app.competitions'),
        ),
        migrations.AddField(
            model_name='result',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats_app.athlete'),
        ),
        migrations.AddField(
            model_name='result',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats_app.competitions'),
        ),
    ]
