# Generated by Django 5.0.7 on 2024-08-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0003_alter_athlete_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='initial_name',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
