# Generated by Django 5.0.7 on 2024-08-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0004_athlete_initial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancetoday',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
    ]
