# Generated by Django 5.0.7 on 2024-08-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0006_distance_remove_distancetoday_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancetoday',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='distancetoday',
            constraint=models.UniqueConstraint(fields=('competitions', 'day', 'order'), name='unique_order_per_day_competition'),
        ),
    ]
