# Generated by Django 5.0.7 on 2024-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0007_alter_distancetoday_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='distancetoday',
            name='unique_order_per_day_competition',
        ),
        migrations.AddConstraint(
            model_name='distancetoday',
            constraint=models.UniqueConstraint(fields=('competitions', 'distance'), name='unique_distance_per_competition'),
        ),
    ]
