# Generated by Django 5.0.7 on 2024-08-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0008_remove_distancetoday_unique_order_per_day_competition_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='distancetoday',
            constraint=models.UniqueConstraint(fields=('competitions', 'day', 'order'), name='unique_order_per_day'),
        ),
    ]
