# Generated by Django 5.0.7 on 2024-08-05 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_school_athlete_school_coach_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.school'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.school'),
        ),
    ]
